### ISSUE TITLE
Heterogeneous information management

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#6]
In SMT, there are two types of information with a completely different data model:
- products resulting from FPs
- the global rights-of-way resulting from contractualization with external surveys

These 2 pieces of information have different attributes. For example, the criteria "Scientific Data Center", "Processing Function", ... do not make sense in the case of global rights-of-way.

The values for these criteria are represented by "null" because these attributes do not exist in the data model for global data sets. 

1st remark: null is not filterable
2nd remark : I don't think we should display these "null" values on the GUI ... it might be weird for the totals ... I don't know how to do it but it's a bit weird. Any idea ?

**Comment by xalioth** [comment]
Thanks for the report,

The first remark (when clicking on "null" the filtering doesn't work) is a recent regression caused by the switch to SQLite on the server, before that it was called "undefined" I think, and it was possible to use for filtering.

Would it be OK to keep "undefined" ? I found this "non value" quit useful as a filter constraint in some case

**Comment by J-Christophe** [comment]
Yes OK for 'undedined'

**Comment by xalioth** [comment]
I fixed the issue, and null is now displayed as 'Undefined' in Italic to show that it's not a real value
